#!/usr/bin/python3.9
import sys
from typing import List, Optional

import typer

from transPYler import transpiler


def main(
        _file: typer.FileText = typer.Argument(
            'index.py',
            metavar='FILE',
            help='Name of file for transpilation'
        ),
        tmpl: List[typer.FileText] = typer.Option(
            None,
            '-t',
            '--templ',
            help='Names of template file'
        ),
        macr: Optional[List[typer.FileText]] = typer.Option(
            [],
            '-m',
            '--macros',
            help='Names of macros file',
            show_default=False
        ),
        out: typer.FileTextWrite = typer.Option(
            sys.stdout,
            '-o',
            '--out',
            help='Output file',
            show_default='stdout'
        ),
        input_lang: Optional[str] = typer.Option(
            'Вetermined by the filename',
            '-l',
            '--lang',
            help='Marking the entrance language (py, hy, coco)'
        )
):
    if not(tmpl):
        typer.echo('You must send at least one template file')
        raise typer.Abort()
    input_lang = {
        'py': 'py',
        'python': 'py',
        'hy': 'hy',
        'hylang': 'hy',
        'coco': 'coco',
        'coconut': 'coconut'
    }.get(_file.name.split('.')[-1])
    tr = transpiler(tmpl, macr)
    result = tr.generate(_file.read(), lang=input_lang)
    if result['recomend']:
        print(result['recomend'])
        print('-' * len(result['recomend']) + '\n')
    print(result['code'], file=out)

if __name__ == '__main__':
     typer.run(main)
